### ISSUE TITLE
keep_output_objs在线程worker_中有值，返回到job.pro->get_future();语句解析后的值为空

### ISSUE THREAD

**Issue by Amanda-Barbara** [shouxieai/kiwi-rknn#2]
您好，咨询您一个问题，我在子线程中fetch_job.pro->set_value(keep_output_objs); 的keep_output_objs的值是有的，并且是正常的，
但返回到主线程中的job.pro->get_future();后的值是空的，请问是什么原因导致的呢？如何解决？谢谢。
job.pro = std::make_shared<std::promise<Output>>();

**Comment by shouxieai** [comment]
啥啥啥？你可以参照我的代码案例。get_future()返回的是future，你得再get_future().get()，拿到的是结果

**Comment by Amanda-Barbara** [comment]
@shouxieai 感谢大佬，这个问题解决了，我执行的时候，生产者-消费者模式实际上还是单线程在运行，主线程往容器中添加输入数据并等待返回的推理结果，子线程负责从容器中拿走输入数据并把推理结果返回给主线程，都是在线程获取锁的情况下才可以执行，您设计的keep_output_objs是为了后续支持模型队列推理的并行计算吗？

**Comment by shouxieai** [comment]
keep_output_objs只是为了让内存持久，避免频繁的分配释放。并行计算其实稍微改改就有了，你可以借鉴这里的：https://github.com/shouxieai/tensorRT_Pro/blob/main/src/application/app_yolo/yolo.cpp。这个是原版

**Comment by Amanda-Barbara** [comment]
@shouxieai 学习到了，谢谢大佬指点。
